AllCops:
  TargetRubyVersion: 2.4

# Lines must be 100 chars or less, default 80.
Metrics/LineLength:
  Max: 100

# Allow variable assignment in combination with 'if' and 'case' statements.
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# Disable check on magic comment to freeze literal string.
Style/FrozenStringLiteralComment:
  Enabled: false
